### ISSUE TITLE
The SafeConfigParser class has been renamed to ConfigParser

### ISSUE THREAD

**Issue by roelmeijer** [Moonbase59/studiodisplay#7]
Great project! can you help to fix the issue to connect the IceCast?

./mqtt-radio.py:60: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instea           d.
  config = configparser.SafeConfigParser()
Read configuration from /home/pi/studiodisplay/python/../config/raspberrypi.cfg
Traceback (most recent call last):
  File "./mqtt-radio.py", line 165, in <module>
    mqttclient = paho.Client(client_id=config.get(my_section, 'client_id'))
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'radio'

**Comment by Moonbase59** [comment]
Fixed in 7d1e4e377d2d29af97401b4653a3903710e3f2ca
